### ISSUE TITLE
Sorting by compute from largest to smallest does not work

### ISSUE THREAD

**Issue by hendrycks** [lightonai/akronomicon#1]

**Comment by slippylolo** [comment]
Hey @hendrycks, 

I reproduce this on my browser, thanks for finding it. 

I think it's because one of the entry has an unknown value ("?"). I will look into finding a workaround.

**Comment by slippylolo** [comment]
Hey, this should be fixed now (there was actually another issue with the main leaderboard using number of parameters as identifying keys for rows, which broke a lot of things!). 

Thanks for reporting the issue @hendrycks.
