### ISSUE TITLE
Open source leaderboard

### ISSUE THREAD

**Issue by StellaAthena** [lightonai/akronomicon#7]
Would there be interest in an option to filter the leaderboard to open source models only? I feel like models like T5, GPT-J, etc which have been released deserve being applauded for that fact. And as a practical matter, for researchers who want to apply these models in their work it takes some searching to find the largest open source models of each type.

**Comment by iacolippo** [comment]
Dear Stella, it would indeed be a nice feature, I really like the idea that practitioners could quickly find the largest open-source model available. We will evaluate the work needed to support it!
